name: mock-entra-oidc-devcontainer

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ../../:/workspace:cached
      - node_modules:/workspace/node_modules
      - tls-private:/workspace/.data/tls-private
    ports:
      - "127.0.0.1:9000:9000"
    networks:
      mock-idp-network:
        aliases:
          - mock-idp.test
    command: sleep infinity
    init: true

volumes:
  node_modules:
  tls-private:

networks:
  mock-idp-network:
    external: true
